title = "Giflib"                                       # From Git
gitRepoUrl = "https://github.com/ukuroks-games/giflib" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "no"

# From git:
organizationName = "Ukuroks Games"
projectName = "Giflib"
url = "https://Ukuroks-Games.github.io"
baseUrl = "/Giflib"
tagline = ""

[footer]
style = "dark"
copyright = "Copyright Â© 2025 Egor00f. Built with Moonwave and Docusaurus"
