[package]
name = "egor00f/giflib"

description = "Library for creating gifs"

version = "0.1.1"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github.com/Ukuroks-games/giflib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["*"]

include = ["src", "src/**", "wally.toml", "README.md", "init.lua"]

private = false

[dependencies]
stdlib = "egor00f/stdlib@0.1.5"

[server-dependencies]


[dev-dependencies]
