[package]
name = "egor00f/giflib"

description = "Library for creating gifs"

version = "0.3.2"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github.com/Ukuroks-games/giflib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

private = false

[dependencies]
stdlib = "egor00f/stdlib@>=0.1.16"

[server-dependencies]


[dev-dependencies]
